// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4zT6QaxmqW-XS72Mn9RxliGWzx4s6ZQ',
    appId: '1:931738425906:web:3fe5b89d6e29555884ba2b',
    messagingSenderId: '931738425906',
    projectId: 'taamin-33650',
    authDomain: 'taamin-33650.firebaseapp.com',
    storageBucket: 'taamin-33650.firebasestorage.app',
    measurementId: 'G-8RXYR5HSQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmC9mHRDQ6qxHOoo0BZcm3XJkkdyHMX0c',
    appId: '1:931738425906:android:a2f0666b31a5c9e084ba2b',
    messagingSenderId: '931738425906',
    projectId: 'taamin-33650',
    storageBucket: 'taamin-33650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXzlsgJPq0TMah-H29taag_wAvUnlTQk4',
    appId: '1:931738425906:ios:49ab0f25affb3e8884ba2b',
    messagingSenderId: '931738425906',
    projectId: 'taamin-33650',
    storageBucket: 'taamin-33650.firebasestorage.app',
    iosBundleId: 'com.robithenha.taamin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_4zT6QaxmqW-XS72Mn9RxliGWzx4s6ZQ',
    appId: '1:931738425906:web:a565fcf06c7cdb6a84ba2b',
    messagingSenderId: '931738425906',
    projectId: 'taamin-33650',
    authDomain: 'taamin-33650.firebaseapp.com',
    storageBucket: 'taamin-33650.firebasestorage.app',
    measurementId: 'G-W6PVTF49XP',
  );

}